export const SET_TOKEN = 'SET_TOKEN';

export const ME_REQUEST = 'ME_REQUEST';
export const ME_REQUEST_SUCCESS = 'ME_REQUEST_SUCCESS';
export const ME_REQUEST_FAILURE = 'ME_REQUEST_FAILURE';

export const SET_POSTS_DATA = 'SET_POSTS_DATA';
export const SET_POSTS_WC_DATA = 'SET_POSTS_WC_DATA';
export const SET_POSTS_DATA_SUCCESS = 'SET_POSTS_DATA_SUCCESS';
export const SET_POSTS_WC_DATA_SUCCESS = 'SET_POSTS_WC_DATA_SUCCESS';
export const SET_POSTS_DATA_FAILURE = 'SET_POSTS_DATA_FAILURE';
export const SET_POSTS_WC_DATA_FAILURE = 'SET_POSTS_WC_DATA_FAILURE';

export const UPDATE_POST_COMMENT_TEXT = 'UPDATE_POST_COMMENT_TEXT';



